### PR TITLE
Adding scripts for creating a Sqlite database of the data

### PR DESCRIPTION
**Pull request by davewalk**
Hello,

Thanks for requesting and releasing this data, it's an interesting dataset to work with. To start I wanted to create a Sqlite database of it and I thought I would share the scripts that I used to do it in case it benefits anyone else in their analysis.

The actual file database itself is too large (almost 300 MB) but I've included a link to download it from the internet to make it even easier for users.

Thanks!

### CODE REVIEW

**Comment by jamestyack** [comment]
Looks good Dave. I've been working on this too and just saw your PR.  I've created logstash config and ES mappings for the data types so we can analyze/search using Kibana. Yeah, pretty interesting data set and seeing some interesting patterns.

**Comment by fulldecent** [comment]
Thank you. I found a data error (2014 file is wrong) and want to correct that first before getting this in.

It is VERY painful to get this XLSX into TSV.

**Comment by davewalk** [comment]
@fulldecent I'm with you on that. So there will be another set of 2014 violations that are different than the 2013 ones? The script will work regardless as long as the name of that file follows the others so it can still be merged after you add that additional file.

After the new file is up I'll update the Sqlite database so it has those 2014 records too.

**Comment by jamestyack** [comment]
Yeah, I noticed the dates for 2014 part file seemed to be older and was curious what the reason was. Have you seen this project? https://github.com/dilshod/xlsx2csv  (there are a few more links at the bottom of the README at that link to other projects too that may help)

**Comment by fulldecent** [comment]
Yes, tried that one. It is killing me.

I used SPSS to do it originally but messed up the 2014 file. Trying to figure out how I did it the first time.

**Comment by fulldecent** [comment]
OK, the 2014 data is now fixed.

I did a force push that messes everything up. It's ugly but I can't have a massive bloated repo!

Please rebase and this is ready to go

**Comment by davewalk** [comment]
@fulldecent This is ready to go.

By the way, I believe the record count discrepancies for 2009, 2010 and 2014 between my table counts and your counts in the README are because you are counting the header as a violation for those years.

For example:

`wc -l citations2010.tsv`
`84088 citations2010.tsv`

`wc -l citations2008.tsv`
`114648 citations2008.tsv`

Thanks!

**Comment by davewalk** [comment]
@fulldecent What do you think?

**Comment by fulldecent** [comment]
Looks great, thank you! Merged

**Pull request merged**
